[site]
title = "baconlzh"
description = "Senior Student at Zhejiang University."
favicon = "/favicon.svg"
last_updated = "February 21, 2026"

[author]
name = "Zhihong Li"
title = "Senior Student"
institution = "Zhejiang University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "baconli@zju.edu.cn"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications/"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services/"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv/"
