[[news]]
date = "2026-01"
content = "My works are accepted by ICA for the first timeðŸŽ‰"

[[news]]
date = "2025-12"
content = "I get an offer from University of Chicago Master Program of Computational Social Science (MACSS) ðŸŽ‰"
